spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/mis
        username: postgres
        password: jocofinki246
        driverClassName: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                show_sql: true
                format_sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
        ddl-auto: update
server:
    port: 8082
