spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/mis
        username: postgres
        password: jocofinki246
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
server:
    port: 8082
jakarta.persistence:
    sharedCache:
        mode: ENABLE_SELECTIVE


